### ISSUE TITLE
Compositor error

### ISSUE THREAD

**Issue by plasticrafting** [TrueOpenVR/SteamVR-TrueOpenVR#1]
Good morning, everyone,

I have a problem with the installation of the OpenVR drivers.
When I install it with SteamVR Settings.exe and launch SteamVR, it recognizes my phone through OpenTrack, but SteamVR tells me that the compositor is not available. As soon as I uninstall the drive through SteamVR Settings.exe, SteamVR works again but no longer recognizes OpenTrack.

(SteamVR version used: 1.3.22)

Anyone have any idea how to fix this?

**Comment by r57zone** [comment]
Hi, I updated the driver, you can try to install, it can now work.

**Comment by plasticrafting** [comment]
Hi, okay i will try this afternoon ;)
