### ISSUE TITLE
Controller buttons are not registering in SteamVR

### ISSUE THREAD

**Issue by hackily** [TrueOpenVR/SteamVR-TrueOpenVR#2]
I'm using [TrueOpenVR 0.7](https://github.com/TrueOpenVR/TrueOpenVR-Core/releases/tag/0.7) (latest release on this repo) with the [SteamVR 0.4 ](https://github.com/TrueOpenVR/SteamVR-TrueOpenVR/releases/tag/0.4) driver, and I am using the provided SplitterAdvance64.dll with the following configurations in the ini:
- HMD set to FreeTrack64.dll
- All of the controller driver options (Position, Rotation, Buttons) to Keyboard64.dll

I see the buttons working in the provided `GetData64.exe` sample

![image](https://user-images.githubusercontent.com/8202335/58752718-daeb1d80-8481-11e9-9571-a952a3517832.png)

But inside of steamVR, the keyboard keys that emulate the buttons don't seem to be triggering anything.

The keyboard keys that move the controller (WASD UHJK) work just fine.

I'm on a Windows 10 machine.

**Comment by r57zone** [comment]
The keys work in games, but do not work in SteamVR (launch menu, browser or etc), I do not know what could be the problem.

Other custom drivers also have this problem, such as the Razer Hydra. It seems they have disabled the launch of the menu and other things for custom drivers.

In any case, this is not critical and allows you to play SteamVR games without problems.

**Comment by apurv1305** [comment]
I'm running into the same issue, those trigger and grip buttons look perfectly fine in the `GetData64.exe` but they do not respond even in the game. I tested it on Beat Saber and got no luck, I was unable to get pass the starting menu page of the game. However all the position and rotation buttons worked fine for both the HMD and the conrollers, and I was able to pass through the privacy policy page (using the ENTER key). 

- I'm on a 64 bit Windows 10 Machine, with the latest iteration of TrueOpenVR
- Both HMD and Controllers are set to `Keyboard.dll`.

**Comment by r57zone** [comment]
Do the buttons work outside of the game? Just on the main SteamVR screen? 
Could also see if they work in SteamVR -> Settings -> Advanced -> Controller Test

**Comment by apurv1305** [comment]
No, they don't work in the settings as well. Another problem was, there is a huge continuous drift when using MPU6050 with Arduino, and it seems quite random, sometimes it detects the rotation in the game and sometimes it simply doesn't no matter how much you try, the direction of controller tend to change everytime, sometimes pitch is interpreted as yaw and vice versa. I will try to give it another shot seeing if butons work or not.
