### ISSUE TITLE
SteamVR displays error 422

### ISSUE THREAD

**Issue by mr555ru** [TrueOpenVR/SteamVR-TrueOpenVR#4]
SteamVR version 1.6.10 (1564442420) shows error 422. It seems to respond to headset movement, but says "Headset is offline" (шлем выключен) in "room setup" and VR apps start in desktop mode.

**Comment by r57zone** [comment]
What equipment do you use? You setup with video instructions? 
VR applications often run in dual mode, any part of it appears on the desktop.

**Comment by mr555ru** [comment]
> What equipment do you use? You setup with video instructions?
> VR applications often run in dual mode, any part of it appears on the desktop.

Just tried to use keyboard, setup with video instructions (https://www.youtube.com/watch?v=HWtdCc_f4ww). Tested on VRChat: it opened in desktop mode. When tested with SteamVR Media Player, menu "Show VR on desktop" (Включить отображение VR) is inaccessible.

**Comment by r57zone** [comment]
Do you use 1 display? Or is an additional VR display also used?

**Comment by mr555ru** [comment]
> 
> 
> Do you use 1 display? Or is an optional VR display also used?

1 display

![изображение](https://user-images.githubusercontent.com/10167440/64068284-be0be500-cc3e-11e9-813d-7accc5c83cad.png)
![изображение](https://user-images.githubusercontent.com/10167440/64068292-cbc16a80-cc3e-11e9-80e5-5daeb771032b.png)

**Comment by r57zone** [comment]
It seem doesn't work with a single display.

**Comment by delekty** [comment]
Так как решить это?

**Comment by r57zone** [comment]
@delekty https://github.com/r57zone/OpenVR-ArduinoHMD & https://github.com/r57zone/OpenVR-OpenTrack
